networks:
    app:
services:
    php-fpm:
        build:
            context: ./.docker/php
        volumes:
            - ./backend:/app
        networks:
            - app

    rabbitmq:
        image: bitnami/rabbitmq:4.0.3
        environment:
            - RABBITMQ_USERNAME=admin
            - RABBITMQ_PASSWORD=admin
            - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
            - RABBITMQ_NODE_NAME=app
        depends_on:
            - php-fpm
        networks:
            - app

    supervisor:
        build:
            context: ./.docker/supervisor
        depends_on:
            - rabbitmq
        volumes:
            - ./backend:/app
            - ./.docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./.docker/supervisor/logs:/var/log/supervisor
        networks:
            - app
