monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: notice
                channels: ["!event"]
                formatter: monolog.formatter.json
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                level: notice
                channels: ["!event"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                formatter: monolog.formatter.json
                max_files: 10

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: notice
                handler: nested
                buffer_size: 50
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: notice
                formatter: monolog.formatter.json
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                level: info
